import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { FormProvider } from "@/contexts/FormContext";
import { CounterProvider } from "@/contexts/CounterContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <FormProvider>
          <CounterProvider>{children}</CounterProvider>
        </FormProvider>
      </body>
    </html>
  );
}
